FROM node:18-buster

RUN mkdir -p /q-server
WORKDIR /q-server
ADD ton-q-server .

RUN npm install -g npm
RUN npm ci
RUN npm run tsc
RUN npm ci --production

EXPOSE 4000

ENTRYPOINT ["node", "index.js"]
