---
- name: Ensure dependencies are installed.
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - jq
      - wget
      - mc
      - git
      - sshpass
      - git
      - python3 
      - libgoogle-perftools-dev
      - rsync
    state: present

- name: Ensure additional dependencies are installed (on Ubuntu < 20.04 and any other systems).
  apt:
    name: gnupg2
    state: present
  when: ansible_distribution != 'Ubuntu' or ansible_distribution_version is version('20.04', '<')

- name: Ensure additional dependencies are installed (on Ubuntu >= 20.04).
  apt:
    name: gnupg
    state: present
  when: ansible_distribution == 'Ubuntu' or ansible_distribution_version is version('20.04', '>=')

- block:
    - name: Install ntp package (timesync is important)
      apt:
        name: chrony
        state: latest
        update_cache: yes

    - name: Copy the chrony.conf file
      template:
        src: ntp.conf.j2
        dest: /etc/chrony/chrony.conf

    - name: reload chrony service
      service:
        name: chronyd
        enabled: yes
        state: restarted
  when: ntp_enabled is defined and ntp_enabled|bool

- name: Set SELinux in permissive mode until the machine is rebooted
  command: setenforce 0
  ignore_errors: true
  changed_when: false