---
- name: Upgrading pip
  pip:
    name:
      - pip
      - passlib
      - jmespath
    state: latest
  vars:
    ansible_python_interpreter: python3

- name: Include os specific tasks
  include_tasks: "{{ ansible_pkg_mgr }}.yaml"

- name: Set timezone to "{{ timezone }}"
  timezone:
    name: "{{ timezone }}"
  when: timezone is defined and timezone | length > 0

- name: Create systemd service "disable-transparent-huge-pages.service"
  copy:
    src: 'disable-transparent-huge-pages.service'
    dest: /etc/systemd/system/disable-transparent-huge-pages.service
  notify: "restart disable-thp"
  when: disable_thp is defined and disable_thp|bool

- name: Linux PAM limits | add or modify nofile limits
  pam_limits:
    domain: "{{ everscale_user }}"
    limit_type: "{{ item.limit_type }}"
    limit_item: "{{ item.limit_item }}"
    value: "{{ item.value }}"
  loop:
    - {limit_type: 'soft', limit_item: 'nofile', value: "{{ soft_nofile }}"}
    - {limit_type: 'hard', limit_item: 'nofile', value: "{{ hard_nofile }}"}
    - {limit_type: 'soft', limit_item: 'nproc', value: "{{ soft_nproc }}"}
    - {limit_type: 'hard', limit_item: 'nproc', value: "{{ hard_nproc }}"}
    - {limit_type: '-', limit_item: 'memlock', value: "{{ memlock }}"}
  when: set_limits is defined and set_limits|bool

- name: Setting kernel parameters
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: true
    state: present
    sysctl_file: "/etc/sysctl.d/99-everscale.conf"
    reload: true
  loop: "{{ sysctl_conf.ever_node | list | unique }}"
  ignore_errors: true
  when: sysctl_set|bool and sysctl_conf | length > 0